var quotes = [
    'Turn your handwriting into a font',
    'Start a blog',
    'Make a moodboard',
    'Rebrand a local charity',
    'Carry a camera everywhere you go for a day',
    'Learn about lateral thinking',
    'Making something with your hands',
    'Craft a mission statement',
    'Design a graphic tee',
    'Perfect the pen tool',
    'Redesign an album cover',
    'Splurge on design books',
    'Visit a museum',
    'Design your personal brand',
    'Rebrand your favorite company',
    'Create a package design for a new drink',
    'Learn handlettering',
    'Create icon illustrations for your favorite food items',
    'Create a homepage design for a product',
    'Create weather icons',
    'Design a brand identity for a festival',
    'Create some iconic landmark illustrations',
    'Design a vintage travel poster',
    'Design a magazine spread',
    'Create a custom sticker design',
    'Draw a design on your morning coffee cup',
    'Create a postcard illustration for the city you live in',
    'Create a tote bag design and help the world become eco-friendly!',
    'Create an animal icon set',
    'Design a poster for your favorite recipe',
    'Create a custom design for a local currency bill',
    'Handletter over a photograph or magazine spread',
    'Mockup a e-commerce page design',
    'Make some soap',
    'Design a repeating pattern for a website background or wallpaper',
    'Re-design UI for e-mail',
    'Film everything you do today and compile it in a video',
    'Learn Photoshop',
    'Learn Illustrator',
    'Learn Figma',
    'Learn Sketch',
    'Learn InDesign',
    'Design custom playing cards',
    'Design a map with your favorite landmarks',
    'Create a character icon for yourself',
    'Read a design manifesto and then create one',
    'Create a family crest',
    'Design a poster for an upcoming event',
    'Design new fonts',
    'Take a break. You deserve it.',
    
]
function newQuote() {
var randomNumber = Math.floor(Math.random() * (quotes.length));
document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}